### ISSUE TITLE
Uncaught Error converting to image format. Check console for more information.

### ISSUE THREAD

**Issue by parthosa** [travs/markdown-pdf#111] opened 2016-06-01 04:34 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package, v1.5.0
### Stack Trace

Uncaught Error converting to image format. Check console for more information.

```
At /home/partho/.atom/packages/markdown-pdf/lib/markdown-pdf.js:166

undefined
```
### Commands

```
     -2:48.8.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  3x -2:48.2.0 emmet:merge-lines (atom-text-editor.editor.is-focused)
     -2:47 core:undo (atom-text-editor.editor.is-focused)
     -2:45.6.0 core:cut (atom-text-editor.editor.is-focused)
  4x -2:44.1.0 core:undo (atom-text-editor.editor.is-focused)
     -2:42.3.0 core:close (atom-text-editor.editor.is-focused)
     -2:41.2.0 application:open-file (atom-text-editor.editor.is-focused)
  2x -2:37.6.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  4x -2:36.8.0 emmet:merge-lines (atom-text-editor.editor.is-focused)
     -2:27.3.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
     -2:20 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -1:57.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:40 application:open-file (atom-text-editor.editor.is-focused)
     -0:20.7.0 markdown-writer:open-cheat-sheet (atom-text-editor.editor.is-focused)
     -0:15.1.0 core:close (div.markdown-preview.native-key-bindings)
     -0:10.9.0 markdown-pdf:convert (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
emmet, v2.4.3
language-babel, v2.23.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
markdown-pdf, v1.5.0
markdown-writer, v2.3.3
merge-conflicts, v1.4.3
minimap, v4.24.3
monokai-seti, v0.7.0
seti-ui, v1.2.3

# Dev
No dev packages
```

**Comment by tmhpfnr** [comment] 2016-09-19 05:17
Same here ...

**Comment by arnolddevos** [comment] 2016-09-20 06:17
Also ...

**Comment by thrly** [comment] 2016-10-12 09:26
Same, is this a result of attempting to convert an image from a local directory? It works fine for me when I use a URL image address...

**Comment by affrae** [comment] 2016-11-08 01:19
Just got it. My markdown file is all text no images...

**Comment by affrae** [comment] 2016-11-08 01:23
Ok in my case, I had a image in the same directory as the markdown file. The image was not referred to in the markdown document at all and had a name unrelated to the name of the markdown file. Take the image out of the directory and conversion works.

**Comment by frivolas** [comment] 2017-01-23 15:33
Just got it as well. No images, pure text.

**Comment by FlyingPiMonster** [comment] 2017-03-04 20:56
I am on a Mac and I get this error whenever I try to use an image that is _not_ hosted locally.

**Comment by lizadams** [comment] 2017-04-24 16:58
I found a few solutions that worked for me.
1) remove an extra backslash that was held over from a different format as an escape key.
User\'s - fixed by removing the backslash.
2) remove an extra backslash at the end of a website http reference
-[Input/Output Applications Programming Interface (I/O API)](https://www.cmascenter.org/ioapi/)
+[Input/Output Applications Programming Interface (I/O API)](https://www.cmascenter.org/ioapi)

3) removed using the website http syntax in the name portion of a link in the document
([<http://www.smoke-model.org/>](http://www.smoke-model.org/))
changed to 
[SMOKE Website](http://www.smoke-model.org/)
4) remove parenthesis from a website name (this breaks the link, but allows the pdf to be created)
changed 
<a href="https://www.airqualitymodeling.org/index.php/CMAQ_version_5.1_(November_2015_release)_Technical_Documentation">Version 5.1</a><br>
to
[Version 5.1](https://www.airqualitymodeling.org/index.php/CMAQ_version_5.1_November_2015_release_Technical_Documentation)<br>

**Comment by travs** [comment] 2017-09-02 17:02
Thank you for these tips Liza.

Have made major changes, so I think this issue is resolved now.
Will close but can happily re-open if we still get it.

**Closed by travs** 2017-09-02 17:02 UTC

**Comment by madsesmith** [comment] 2017-09-06 15:52
I am just getting this error for the first time after updating to markdown-pdf v2.0.4 using Atom 1.19.3 on macOS. I tried in files that worked yesterday before I updated, following Liza's tips above, and in a file that just had a single text line. Every time `Uncaught Error converting to image format.`

**Comment by travs** [comment] 2017-09-07 09:01
@madsesmith 
Ok thank you for the report Madeline, will look into better error reporting so we can sort out what the problem is.

In the meantime you can revert to an old version by doing `apm install markdown-pdf@1.5.4` (or whatever other version number) from the command line.
If you don't have `apm` available in the terminal try [this](https://apple.stackexchange.com/questions/131348/how-to-make-command-apm-available-after-installing-atom) to get it.

Sorry that there has to be a workaround for now, but there were major updates to the project.
Hopefully we can find the underlying issue and fix it in a new version.

Also, if it's not secret information, would you put the content you are trying to convert in a [gist](https://gist.github.com/) so I can have a try locally? Thanks.

**Comment by madsesmith** [comment] 2017-09-11 13:41
@travs 
Last Wednesday no files would convert for me. Not even a file that contained only `#Test`. Today all of the files I've run before are working. It must just have been a "bad-day-nothing-is-going-to-work" kind of things and not actually a bug...

**Comment by travs** [comment] 2017-09-11 15:35
@madsesmith Huh, ok, I will leave this one closed, but still work to have better error messages in the future.
Thanks for following up!

**Comment by madsesmith** [comment] 2017-09-18 12:18
@travs so I was getting the error again... but after a reboot of my entire mac it is now converting again. restarting atom alone was not enough to fix it. i think a reboot is what made it suddenly start working again last week as well.

**Comment by madsesmith** [comment] 2017-09-18 12:33
I take that back. I was able to convert one file after restarting, now I'm getting this error again with every file I try. Here's [the file](https://gist.github.com/madsesmith/0865cc20689d2d465643692ed8e6451b) I just converted a few minutes ago for [the styles.less issue](https://github.com/travs/markdown-pdf/issues/165#issuecomment-330203967) but now get an error when I try to convert...
