### ISSUE TITLE
pdf file only have  content in clipboard

### ISSUE THREAD

**Issue by zewenhs** [travs/markdown-pdf#202] opened 2018-12-29 12:05 UTC
why the pdf file converted from md file only have  content in my clipboard? 

Ubuntu 14.04
Atom 1.33.1
markdown-pdf:2.2.0

But  it works well in the win7 with the same version Atom and markdown-pdf.

Please help!!!

![image](https://user-images.githubusercontent.com/7780577/50538088-b3c3b380-0ba4-11e9-9157-f9bebd52a657.png)

**Comment by ryeates** [comment] 2019-01-17 12:03
Found the root cause. `markdown-pdf` seems to require `markdown-preview` to generate the HTML to convert to PDF.  `markdown-preview` seems broken as of current version and you can see this by trying to `Save As Html..` which fails to produce anything except the content of your clipboard.    
   
Hacky workaround is to open the console and inspect element of the preview. Copy the HTML elements into a new file. Then invoke `Markdown to PDF`. It will moan but will produce the pdf with some minor wierdness (mostly missing CSS issues)

**Comment by MCDELTAT** [comment] 2019-05-15 17:35
Just wanted to confirm I have the same bug:
Ubuntu 18.04 (Linux Mint 19.1)
Atom 36.1
Markdown-pdf 2.2.0

**Comment by travs** [comment] 2020-03-10 03:44
This should be fixed upstream in `markdown-preview` now, and we also only rely on that for fallback converting at this time

**Closed by travs** 2020-03-10 03:44 UTC
