### ISSUE TITLE
No word wrapping in code blocks.

### ISSUE THREAD

**Issue by synthecypher** [travs/markdown-pdf#85] opened 2015-09-08 10:11 UTC
A word wrap option would be good or something.
![image](https://cloud.githubusercontent.com/assets/1833542/9732229/3b56d2e4-561a-11e5-9076-388fbfc82976.png)

**Comment by travs** [comment] 2016-03-26 02:48
@synthecypher 
Major updates recently. 
Does this still occur?

**Comment by lukehsiao** [comment] 2016-04-04 20:04
Using `markdown-pdf` version 1.5.0, this still occurs for me:

![image](https://cloud.githubusercontent.com/assets/7573542/14261503/b99712aa-fa65-11e5-8173-c6240cce2c78.png)

**Comment by eonist** [comment] 2016-04-19 07:25
Still occurs. I guess if there was a way to force Atom to not wrap code blocks?

**Comment by jack6liu** [comment] 2017-03-02 07:02
till now, still no word wrap in code blocks

**Comment by alexis-renard** [comment] 2017-06-29 21:09
Still waiting for a support here, it's pretty anoying manually wrap the code :/

**Comment by vaughany** [comment] 2017-08-25 14:25
Just to add my 2p, I'm also in a position where I have long code blocks which are disappearing off the right-hand side due to their length.

**Comment by travs** [comment] 2017-09-02 16:59
duplicate of #21; please refer to that issue. Also will be looking for a fix for this in the next little while

**Closed by travs** 2017-09-02 16:59 UTC

**Comment by skofgar** [comment] 2021-09-26 03:54
This problem is still happening for me. I don't see a scrollbar, but code doesn't wrap and just goes off the screen.

**Comment by danieltaylor** [comment] 2021-11-27 01:36
@skofgar Same here.  Adding `  white-space: pre-wrap;` to the `.markdown-body pre code { ... }` block in `markdown-pdf/node_modules/mdpdf/src/assets/github-markdown-css.css` as suggested [here](https://github.com/travs/markdown-pdf/issues/21#issuecomment-392895273) fixed the issue for me.
