### ISSUE TITLE
Markdown Last Header not formatted when exporting

### ISSUE THREAD

**Issue by jackieli19** [travs/markdown-pdf#214] opened 2019-08-19 14:59 UTC
### Issue description
When I try to output the PDF version from my .md using markdown-pdf package , the **last** header always cannot be transferred. All other headers are formatted well. i.e:

my .md:
#### xxx(last header)
output: #### xxx

### Steps to reproduce

**Expected behavior:** All headers will be formatted well.

**Actual behavior:** The last one always cannot be detected as a header.

### Versions

Windows 10: Atom 1.40.0

**Comment by travs** [comment] 2020-03-10 02:39
Hi there. I am unable to reproduce this locally. Since the issue is so old and we have changed our backend, I will close it.
If it still occurs for you though, please re-open it and provide a full sample markdown file that causes the error.

**Closed by travs** 2020-03-10 02:39 UTC
