### ISSUE TITLE
Local image doesn't show up on PDF.

### ISSUE THREAD

**Issue by dalzzing2** [travs/markdown-pdf#126] opened 2016-09-23 06:39 UTC
I write new image path like this.

`<img src="C:\Users\PSH\Pictures\client 32bit\install_1.jpg" alt="Install_1" style="width : 350px;"/>`

I can look the image on PDF preview(ctl + shift +m) but dosen't show the image up in PDF(ctl + shift + c).

Only "Install_1" and the image frame show up on PDF.

**Comment by nsecrist** [comment] 2016-10-11 14:05
I have been experiencing the same issue.

![markdown_pdf_image_bug](https://cloud.githubusercontent.com/assets/403402/19273319/b7a16eb6-8f91-11e6-9666-0a9031d0428b.png)

From the screenshot you can see that the image appears in the preview, but once you convert to pdf, the only a placeholder with the image title appears.

**Comment by aleksandr-m** [comment] 2016-10-14 18:19
Duplicate of #109.

**Comment by travs** [comment] 2017-06-15 06:24
Closing as duplicate

**Closed by travs** 2017-06-15 06:24 UTC
