### ISSUE TITLE
Docs: Not precise on how to use 'convert' command

### ISSUE THREAD

**Issue by joallard** [travs/markdown-pdf#137] opened 2016-12-06 21:09 UTC
It says 'use the convert command'. Where? How?

**Comment by joallard** [comment] 2016-12-07 20:03
I got it. The readme should say:

```
Go to `Packages > Markdown PDF > Convert`
```

To be even better, the option could be called "Generate PDF", that way we could type 'PDF' when using the command palette.

**Comment by travs** [comment] 2017-06-15 06:24
Closing as duplicate of #142 (even though this one came first)

**Closed by travs** 2017-06-15 06:24 UTC
