### ISSUE TITLE
markdown-pdf not rendering latex in pdf

### ISSUE THREAD

**Issue by adamnicholasprice** [travs/markdown-pdf#186] opened 2018-03-20 20:05 UTC
## Here is a section of code from a .md document that I am trying to convert. 
```
#### Question 1a.

$$
\mathbf{S} = \left[\begin{array}
{rr}
10.9 & -12.7 \\
-12.7 & 26.7
\end{array}\right]
$$
```

## In the markdown-preview within Atom this is the output I get:
![screen shot 2018-03-20 at 1 00 10 pm](https://user-images.githubusercontent.com/29460883/37679658-cb4eadac-2c3e-11e8-9583-932906cf79a0.png)

## However, once I ctrl-shift-c within the .md document, the output from the pdf looks like this:
![screen shot 2018-03-20 at 1 00 32 pm](https://user-images.githubusercontent.com/29460883/37679677-e4689b18-2c3e-11e8-87ed-2c43ce78e5d5.png)

## I have the following versions of atom, pandoc, and LaTeX:
atom 1.25.0
pandoc 1.19.2.1
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3

### Any suggestions?

**Comment by travs** [comment] 2018-05-26 20:06
Do you use `markdown-preview-plus`, or another viewer, by any chance?
I have pasted this latex code into a md document and the preview does not give the latex output you have shown.

Also it may be worth trying the `force fallback` mode in this package's settings, which takes the html directly from the preview pane.

**Comment by travs** [comment] 2018-05-26 22:43
Closing as duplicate of https://github.com/travs/markdown-pdf/issues/117

**Closed by travs** 2018-05-26 22:43 UTC
Labels: feature request, help wanted

**Comment by wzy6642** [comment] 2020-02-24 13:16
I want to know how to deal with this problem. Thanks!!
