### ISSUE TITLE
Bold or italicized characters aren't rendered correctly

### ISSUE THREAD

**Issue by SpencerKaiser** [travs/markdown-pdf#197] opened 2018-07-02 15:57 UTC
### Prerequisites
* [ ] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
  - For some reason I can't install new packages in Safe mode. I get the following error: `Could not resolve 'markdown-pdf' to a package path`
  - **NOTE**: I am currently using macOS Mojave Beta 2. I haven't tried this tool on any other version of macOS and a [similar tool](https://www.npmjs.com/package/markdown-pdf) has the same issue.
* [X] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues

### Issue description
Whenever I generate a PDF, any items that are italicized or in bold are not rendered appropriately. For example, **pdf** looks like pdf.

### Steps to reproduce
Create a markdown document, enter the text below, and render the document to PDF using this package.

The word **BOLD** should look bold.

**Expected behavior:** [What you expect to happen]
`**BOLD**` -> **BOLD**

**Actual behavior:** [What actually happens]
`**BOLD**` -> BOLD

[This file](https://github.com/travs/markdown-pdf/files/2155894/Test.pdf) is the output from the text below in a file titled `Test.md`.

### Input
`The word **BOLD** should look bold.`

### Versions
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 2.7.10
git 2.15.2

**Comment by Akaizoku** [comment] 2018-10-01 16:50
It works properly for me on Windows and, IIRC, I never encountered this issue on macOS either.

Though I have issues with the letter "w" as you can see... (see issue #178)

### Output

![bold](https://user-images.githubusercontent.com/8892526/46302593-54540880-c5a1-11e8-9011-eb420329ceec.png)

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 3.6.5
git
visual studio 2015

Microsoft Windows 10 Version 1709 (OS Build 16299.371)

**Comment by LowKostKustomz** [comment] 2018-10-12 09:53
The same issue with **BOLD** word is not bold. Fix it, please.

**Comment by luisarojas** [comment] 2018-11-28 18:46
Same issue for me (on macOS Mojave, version 10.14.1). Atom version 1.32.2.

**Comment by rsnitsch** [comment] 2018-12-11 12:49
Same issue here.

Atom 1.33.0, mac OS 10.14.1 (Mojave), markdown-pdf 2.2.0.

**Comment by daviscyl** [comment] 2019-01-19 03:40
same issue here
Atom 1.34.0 x64, mac OS 10.14.2 (Mojave), markdown-pdf 2.2.0.

**Comment by diplodata** [comment] 2019-02-13 12:14
Still (Dre).. Atom 1.34.0 mac OS 10.14.3

**Comment by MADdelaRosa** [comment] 2019-07-13 00:43
I am having this same problem. While writing in Atom, markdown-preview renders all text correctly (boldface and italics), but when once a pdf is created using markdown-pdf, the boldface text is rendered as regular text (the italics text, however, is rendered correctly for me). I am at a loss after trying unsuccessfully to find a reason for this bug. Any help is appreciated.

Using Mojave 10.14.5, Atom 1.37.0, markdown-pdf 2.2.0.

**Comment by rilla** [comment] 2019-08-01 11:47
I've found a workaround that worked for me:

- markdown-pdf uses [mdpdf](https://github.com/BlueHatbRit/mdpdf) as its rendering engine
- mdpf had this same issue reported a while back: https://github.com/BlueHatbRit/mdpdf/issues/59
- the issue is resolved in newer versions of mdpdf (> 2.0.0)

So to solve the problem locally you can just:

```
cd  ~/.atom/packages/markdown-pdf/node-modules
rm -rf mdpdf
npm install mdpdf
```

After reloading Atom the problem should be gone.

Probably worth considering a bump of mdpdf version in markdown-pdf's dependencies. I'd open a PR myself, but I have zero familiarity with Node.

**Comment by doits** [comment] 2019-10-11 10:26
I had to `npm install mdpdf@2.0.4` to make it actually fetch the latest version and fiddle with custom styles to increase the font-size (was way too small after the update), but now it works, thanks!

**Comment by travs** [comment] 2020-03-10 03:50
We upgraded to a new mdpdf lately, so this is no longer an issue I think

**Closed by travs** 2020-03-10 03:50 UTC
