### ISSUE TITLE
Cannot find module less

### ISSUE THREAD

**Issue by chopin2712** [travs/markdown-pdf#208] opened 2019-04-11 18:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.10
**Thrown From**: [markdown-pdf](https://github.com/travs/markdown-pdf) package 2.2.0

### Stack Trace

Failed to activate the markdown-pdf package

```
At Cannot find module 'less'

Error: Cannot find module 'less'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/snap/atom/224/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at loadDeps (/home/chopin/Downloads/markdown-pdf-master/lib/markdown-pdf.js:14:10)
    at Object.activate (/home/chopin/Downloads/markdown-pdf-master/lib/markdown-pdf.js:74:5)
    at Package.activateNow (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:2921510)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:1190169)
    at Emitter.emit (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:1191610)
    at CommandRegistry.handleCommandEvent (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:349687)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:1230796)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:1226930)
    at WindowEventHandler.handleDocumentKeyEvent (/snap/atom/224/usr/share/atom/resources/app/static/<embedded>:11:285234)
```

### Commands

```
     -0:12.5.0 markdown-pdf:convert (input.hidden-input)
```

### Non-Core Packages

```
markdown-pdf 2.2.0 
markdown-themeable-pdf 1.2.1 
micro undefined 
```

**Comment by travs** [comment] 2020-03-10 03:19
Duplicate of #181

**Closed by travs** 2020-03-10 03:19 UTC
