### ISSUE TITLE
Generated PDF not highlighting syntax

### ISSUE THREAD

**Issue by dotnetdan** [travs/markdown-pdf#20] opened 2015-01-02 21:26 UTC
The generated PDF's aren't including any syntax highlighting.  My code sample is C#, I tried both cs and csharp.

# Test
 
 ```csharp
 public class FooClass
 {
     public void FooMethod(FooParameter p)
     {
         Console.WriteLine(p);
     }
 }
 ```

**Comment by travs** [comment] 2015-01-02 23:18
@dotnetdan 
Hmm, what OS are you running?
Also, do you know if other languages show syntax highighting?

Thanks for the bug report!

**Comment by dotnetdan** [comment] 2015-01-05 15:08
I'm on Windows 7 64 bit.

I tried Python as well and had the same issue.

In editor:
![image](https://cloud.githubusercontent.com/assets/500965/5614791/a3425942-94c2-11e4-8fdf-6cfceb081ffb.png)


PDF:
![image](https://cloud.githubusercontent.com/assets/500965/5614811/cbba1a7c-94c2-11e4-8afb-234974f20b9f.png)

**Comment by travs** [comment] 2015-01-07 01:01
@dotnetdan 
Ok, I think I know what the problem is, but to be sure could you open the developer console (`View > Developer > Toggle developer tools`) and give me the results of this command?

```js
for(i of atom.themes.getActiveThemes()){console.log(i.name)}
```

**Comment by dotnetdan** [comment] 2015-01-07 02:07
Sure,

```
>for(i of atom.themes.getActiveThemes()){console.log(i.name)}
 solarized-dark-syntax VM954:2
 seti-ui VM954:2
 undefined
```

**Comment by travs** [comment] 2015-01-07 23:48
Ok, it's not what I thought but I believe I may have found a fix.

Will take some time to implement, but thank you for pointing this out :bug:

**Comment by dotnetdan** [comment] 2015-01-09 22:24
Ok, thanks.  Let me know if I can help in any way.  I am using this package a lot and would be glad to help.

**Comment by travs** [comment] 2015-01-10 14:46
Alright, I think I have it fixed now.

Have a look at the settings for this package (`ctrl-,`) and change `Marked` to `Markdown-Preview` under `Rendering`.

Let me know if this works/any bugs you see with it, and also if #21 is still a problem (I think it will be, but you never know).

Will probably implement as the default renderer instead of `Marked` if it ends up being stable.

Thanks for your help!

**Comment by dotnetdan** [comment] 2015-01-12 21:42
I'm not able to install it through the IDE.  I keep getting this error:

Installing “markdown-pdf@1.2.11” failed.Hide output…

> phantomjs@1.9.13 install C:\Users\dling\AppData\Local\Temp\apm-install-dir-115012-14852-12l5vbb\node_modules\markdown-pdf\node_modules\html-pdf\node_modules\phantomjs
> node install.js


npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/html-pdf
npm http 304 https://registry.npmjs.org/marked
npm http 304 https://registry.npmjs.org/html-pdf
npm http GET https://registry.npmjs.org/phantomjs
npm http 304 https://registry.npmjs.org/phantomjs
npm http GET https://registry.npmjs.org/adm-zip/0.4.4
npm http GET https://registry.npmjs.org/progress/1.1.8
npm http GET https://registry.npmjs.org/kew/0.4.0
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/npmconf/2.0.9
npm http GET https://registry.npmjs.org/request-progress/0.3.1
npm http GET https://registry.npmjs.org/request/2.42.0
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http 304 https://registry.npmjs.org/adm-zip/0.4.4
npm http 304 https://registry.npmjs.org/kew/0.4.0
npm http 304 https://registry.npmjs.org/request-progress/0.3.1
npm http 304 https://registry.npmjs.org/progress/1.1.8
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/npmconf/2.0.9
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/request/2.42.0
npm http GET https://registry.npmjs.org/throttleit
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/hawk/1.1.1
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/uid-number/0.0.5
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/hawk/1.1.1
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/throttleit
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/uid-number/0.0.5
npm http GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles

**Comment by travs** [comment] 2015-01-12 23:52
@dotnetdan 

Apparently this [is an issue](https://github.com/npm/npm/issues/7093) with at least one other Win7 user.

Since apm apparently uses an older version of npm, this *may* be the source of the issue.

I will ping the apm team with an issue on this shortly, and see if we can't get this resolved.

**Comment by Nicnl** [comment] 2015-01-13 14:58
The generated PDF have black text and the separator isn't rendering.
![md_1](https://cloud.githubusercontent.com/assets/1387951/5722452/88fd490e-9b3c-11e4-933b-
68692b2a5ad2.jpg)
![md_2](https://cloud.githubusercontent.com/assets/1387951/5722453/88ffc13e-9b3c-11e4-8ba4-038e6bfee641.jpg)


I've modified the .js script to output the html code.
![md_3](https://cloud.githubusercontent.com/assets/1387951/5722458/89f70f20-9b3c-11e4-9913-fc6f5f5aab79.jpg)

Problem 1:
![md_4](https://cloud.githubusercontent.com/assets/1387951/5722454/893b529e-9b3c-11e4-91bd-f10a82198c2b.jpg)

Problem 2:
![md_5](https://cloud.githubusercontent.com/assets/1387951/5722455/89465bd0-9b3c-11e4-8655-f3b24fd7a4f5.jpg)

Ugly fix: 
![md_6](https://cloud.githubusercontent.com/assets/1387951/5722456/8984733e-9b3c-11e4-93d0-7d54db20143f.jpg)

The output pdf:
![md_7](https://cloud.githubusercontent.com/assets/1387951/5722457/898e375c-9b3c-11e4-88a3-81982f3e864b.jpg)

Apparently, markdown-pdf have some problems rendering `:host` and `atom://` URLs.

**Comment by dotnetdan** [comment] 2015-01-13 17:24
@travs I discovered that the package wasn't installing due to a problem on my machine - my environment PATH was exceeding the maximum length allowed by Windows.  After fixing that, I was able to install and test.  Sorry about the false alarm!

My results are the same as reported by @Nicnl above.

**Comment by travs** [comment] 2015-01-15 16:43
@Nicnl 

Hey thanks for the report :bug: 
Could you make a pull request with those changes?

At least it works; we can focus on elegance later.

**Comment by travs** [comment] 2015-01-19 19:45
@dotnetdan 
Going to close this now. Is the latest patch working for you?

**Closed** 2015-01-19 19:45 UTC
Labels: bug
